language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "7"
notifications:
  email: false
script: yarn test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
