const constants = {
  unknown: 'unknown',
  loading: 'loading',
  loadingData: 'Loading data',
  widgetType: {
    number: 'number',
    funnel: 'funnel',
    breakdown: 'breakdown',
    history: 'history',
    text: 'text',
    finance: 'finance',
    weather: 'weather',
    github: 'githubPr',
    pieChart: 'pieChart',
    instagram: 'instagram',
  },
  iconType: {
    jira: 'jira',
    newrelic: 'newrelic',
    google: 'google',
    calendar: 'calendar',
    weather: 'weather',
    statuscake: 'statuscake',
    twitter: 'twitter',
    github: 'github',
    instagram: 'instagram',
  },
  iconSrc: {
    jira: 'icons/icon-jira-logo.png',
    newrelic: 'icons/icon-newrelic-logo.png',
    google: 'icons/icon-google-logo.png',
    calendar: 'icons/icon-calendar-logo.png',
    weather: 'icons/icon-weather-logo.png',
    statuscake: 'icons/icon-statuscake-logo.png',
    twitter: 'icons/icon-twitter-logo.png',
    github: 'icons/icon-github-logo.png',
    instagram: 'icons/icon-instagram-logo.png',
  },
  chartColor: {
    green: '#6abf69',
    blue: '#039be5',
    red: '#ff6659',
    tickColor: '#b7b7b7',
  },
  draggableType: {
    smallWidget: 'smallWidget',
  },
  draggingOpacity: 0.5,
};

export default constants;
