import reducers from './index';

test('reducers sequence', () => {
  // Maintenance: This test can be easy updated using the "Redux DevTools" extension for Chrome
  // Go to the Redux tab, Shift-select all actions on the left side and go to "Tests" on the right side.
  let state;
  state = reducers(
    {
      number: {},
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [],
      newRelicWebsiteFunnel: [],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'weekNumber', current: 28 } },
  );
  expect(state).toEqual({
    number: { weekNumber: { current: 28 } },
    bugsHistory: { history: [] },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: { weekNumber: { current: 28 } },
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [],
      newRelicWebsiteFunnel: [],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'newRelicLoadTime', current: 0.2755303312302837 } },
  );
  expect(state).toEqual({
    number: { weekNumber: { current: 28 }, newRelicLoadTime: { current: 0.2755303312302837 } },
    bugsHistory: { history: [] },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: { weekNumber: { current: 28 }, newRelicLoadTime: { current: 0.2755303312302837 } },
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [],
      newRelicWebsiteFunnel: [],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'newRelicErrors', current: 0, previous: 0 } },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
    },
    bugsHistory: { history: [] },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
      },
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [],
      newRelicWebsiteFunnel: [],
    },
    {
      type: 'RECEIVE_NEWRELICERRORBREAKDOWN',
      payload: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
    },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
    },
    bugsHistory: { history: [] },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
      },
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'newRelicSuccessfulBookings', current: 15, previous: 20 } },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
    },
    bugsHistory: { history: [] },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
        newRelicSuccessfulBookings: { current: 15, previous: 20 },
      },
      bugsHistory: { history: [] },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [],
    },
    {
      type: 'RECEIVE_BUGSHISTORY',
      payload: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
    },
    bugsHistory: {
      history: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
        newRelicSuccessfulBookings: { current: 15, previous: 20 },
      },
      bugsHistory: {
        history: [
          { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
          { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
          { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
          { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
          { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
          { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
          { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
          { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
          { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
          { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
          { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
          { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
          { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
          { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
          { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
          { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
          { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
          { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
          { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
          { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
          { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
          { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
          { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
          { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
          { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
          { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
          { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        ],
      },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [],
    },
    {
      type: 'RECEIVE_NEWRELICWEBSITEFUNNEL',
      payload: [
        { name: 'Home Page', count: 723 },
        { name: 'Search Page', count: 98 },
        { name: 'Checkout Step 1', count: 2 },
        { name: 'Checkout Step 2', count: 0 },
        { name: 'Checkout Step 3', count: 0 },
        { name: 'Checkout Success', count: 0 },
      ],
    },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
    },
    bugsHistory: {
      history: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [
      { name: 'Home Page', count: 723 },
      { name: 'Search Page', count: 98 },
      { name: 'Checkout Step 1', count: 2 },
      { name: 'Checkout Step 2', count: 0 },
      { name: 'Checkout Step 3', count: 0 },
      { name: 'Checkout Success', count: 0 },
    ],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
        newRelicSuccessfulBookings: { current: 15, previous: 20 },
      },
      bugsHistory: {
        history: [
          { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
          { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
          { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
          { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
          { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
          { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
          { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
          { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
          { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
          { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
          { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
          { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
          { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
          { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
          { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
          { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
          { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
          { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
          { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
          { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
          { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
          { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
          { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
          { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
          { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
          { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
          { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        ],
      },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [
        { name: 'Home Page', count: 723 },
        { name: 'Search Page', count: 98 },
        { name: 'Checkout Step 1', count: 2 },
        { name: 'Checkout Step 2', count: 0 },
        { name: 'Checkout Step 3', count: 0 },
        { name: 'Checkout Success', count: 0 },
      ],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'newRelicUniqueSessions', current: 157, previous: 176 } },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
      newRelicUniqueSessions: { current: 157, previous: 176 },
    },
    bugsHistory: {
      history: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [
      { name: 'Home Page', count: 723 },
      { name: 'Search Page', count: 98 },
      { name: 'Checkout Step 1', count: 2 },
      { name: 'Checkout Step 2', count: 0 },
      { name: 'Checkout Step 3', count: 0 },
      { name: 'Checkout Success', count: 0 },
    ],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
        newRelicSuccessfulBookings: { current: 15, previous: 20 },
        newRelicUniqueSessions: { current: 157, previous: 176 },
      },
      bugsHistory: {
        history: [
          { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
          { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
          { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
          { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
          { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
          { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
          { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
          { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
          { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
          { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
          { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
          { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
          { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
          { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
          { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
          { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
          { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
          { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
          { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
          { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
          { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
          { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
          { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
          { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
          { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
          { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
          { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        ],
      },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [
        { name: 'Home Page', count: 723 },
        { name: 'Search Page', count: 98 },
        { name: 'Checkout Step 1', count: 2 },
        { name: 'Checkout Step 2', count: 0 },
        { name: 'Checkout Step 3', count: 0 },
        { name: 'Checkout Success', count: 0 },
      ],
    },
    { type: 'RECEIVE_NUMBER', payload: { key: 'newRelicCliErrors', current: 1 } },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
      newRelicUniqueSessions: { current: 157, previous: 176 },
      newRelicCliErrors: { current: 1 },
    },
    bugsHistory: {
      history: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
    jiraIssues: { blockers: 0, criticals: 0, others: 0 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [
      { name: 'Home Page', count: 723 },
      { name: 'Search Page', count: 98 },
      { name: 'Checkout Step 1', count: 2 },
      { name: 'Checkout Step 2', count: 0 },
      { name: 'Checkout Step 3', count: 0 },
      { name: 'Checkout Success', count: 0 },
    ],
  });
  state = reducers(
    {
      number: {
        weekNumber: { current: 28 },
        newRelicLoadTime: { current: 0.2755303312302837 },
        newRelicErrors: { current: 0, previous: 0 },
        newRelicSuccessfulBookings: { current: 15, previous: 20 },
        newRelicUniqueSessions: { current: 157, previous: 176 },
        newRelicCliErrors: { current: 1 },
      },
      bugsHistory: {
        history: [
          { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
          { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
          { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
          { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
          { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
          { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
          { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
          { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
          { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
          { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
          { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
          { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
          { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
          { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
          { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
          { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
          { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
          { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
          { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
          { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
          { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
          { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
          { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
          { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
          { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
          { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
          { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
          { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        ],
      },
      jiraIssues: { blockers: 0, criticals: 0, others: 0 },
      newRelicErrorBreakdown: [
        { name: 'Common\\Error\\Exception\\Error', count: 8 },
        { name: 'Common\\Error\\Exception\\Notice', count: 1 },
        { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
      ],
      newRelicWebsiteFunnel: [
        { name: 'Home Page', count: 723 },
        { name: 'Search Page', count: 98 },
        { name: 'Checkout Step 1', count: 2 },
        { name: 'Checkout Step 2', count: 0 },
        { name: 'Checkout Step 3', count: 0 },
        { name: 'Checkout Success', count: 0 },
      ],
    },
    { type: 'JIRAISSUES_RECEIVE', payload: { blockers: 0, criticals: 0, others: 9 } },
  );
  expect(state).toEqual({
    number: {
      weekNumber: { current: 28 },
      newRelicLoadTime: { current: 0.2755303312302837 },
      newRelicErrors: { current: 0, previous: 0 },
      newRelicSuccessfulBookings: { current: 15, previous: 20 },
      newRelicUniqueSessions: { current: 157, previous: 176 },
      newRelicCliErrors: { current: 1 },
    },
    bugsHistory: {
      history: [
        { date: '4. Januar', openBugs: 23, solvedBugs: 0, newBugs: 0 },
        { date: '19. Januar', openBugs: 28, solvedBugs: 8, newBugs: 0 },
        { date: '27. Januar', openBugs: 20, solvedBugs: 5, newBugs: 0 },
        { date: '7. Februar', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '13. Februar', openBugs: 20, solvedBugs: 3, newBugs: 0 },
        { date: '22. Februar', openBugs: 23, solvedBugs: 7, newBugs: 1 },
        { date: '23. Februar', openBugs: 25, solvedBugs: 0, newBugs: 0 },
        { date: '1. März', openBugs: 25, solvedBugs: 6, newBugs: 0 },
        { date: '2. März', openBugs: 27, solvedBugs: 3, newBugs: 1 },
        { date: '9. März', openBugs: 28, solvedBugs: 7, newBugs: 2 },
        { date: '16. März', openBugs: 31, solvedBugs: 0, newBugs: 4 },
        { date: '20. März', openBugs: 31, solvedBugs: 3, newBugs: 0 },
        { date: '27. März', openBugs: 27, solvedBugs: 6, newBugs: 2 },
        { date: '30. März', openBugs: 28, solvedBugs: 1, newBugs: 0 },
        { date: '5. April', openBugs: 31, solvedBugs: 12, newBugs: 1 },
        { date: '10. April', openBugs: 37, solvedBugs: 2, newBugs: 4 },
        { date: '13. April', openBugs: 41, solvedBugs: 5, newBugs: 4 },
        { date: '20. April', openBugs: 34, solvedBugs: 6, newBugs: 5 },
        { date: '24. April', openBugs: 33, solvedBugs: 1, newBugs: 0 },
        { date: '27. April', openBugs: 25, solvedBugs: 11, newBugs: 1 },
        { date: '4. Mai', openBugs: 23, solvedBugs: 10, newBugs: 3 },
        { date: '11. Mai', openBugs: 21, solvedBugs: 10, newBugs: 4 },
        { date: '18. Mai', openBugs: 22, solvedBugs: 6, newBugs: 3 },
        { date: '1. Juni', openBugs: 25, solvedBugs: 1, newBugs: 2 },
        { date: '8. Juni', openBugs: 25, solvedBugs: 8, newBugs: 3 },
        { date: '15. Juni', openBugs: 21, solvedBugs: 7, newBugs: 4 },
        { date: '16. Juni', openBugs: 22, solvedBugs: 1, newBugs: 0 },
        { date: '20. Juni', openBugs: 22, solvedBugs: 3, newBugs: 0 },
        { date: '26. Juni', openBugs: 23, solvedBugs: 0, newBugs: 0 },
      ],
    },
    jiraIssues: { blockers: 0, criticals: 0, others: 9 },
    newRelicErrorBreakdown: [
      { name: 'Common\\Error\\Exception\\Error', count: 8 },
      { name: 'Common\\Error\\Exception\\Notice', count: 1 },
      { name: 'Common\\StateMachine\\Service\\StateMachine\\Exception\\LockException', count: 1 },
    ],
    newRelicWebsiteFunnel: [
      { name: 'Home Page', count: 723 },
      { name: 'Search Page', count: 98 },
      { name: 'Checkout Step 1', count: 2 },
      { name: 'Checkout Step 2', count: 0 },
      { name: 'Checkout Step 3', count: 0 },
      { name: 'Checkout Success', count: 0 },
    ],
  });
});
